name: R

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  merge_group:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        r-version: ['oldrel-1', 'release', 'devel']
        os: [ubuntu-latest, macos-latest]

    env:
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: yes
      # R
      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.r-version }}
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check
      - if: runner.os == 'macOS'
        run: brew install --cask xquartz
      # Python & Jupyter
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: 'pip'
          cache-dependency-path: 'tests/requirements.txt'
      - run: pip install -r tests/requirements.txt
      # Checks
      - uses: r-lib/actions/check-r-package@v2
