name: R

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        r-version: ['oldrel-1', 'release']
        os: [ubuntu-latest, macos-latest]

    env:
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: yes
      # R
      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.r-version }}
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check
      # Python & Jupyter
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - run: pip install jupyter jupyter-client ndjson-testrunner jupyter-kernel-test
      # Checks
      - uses: r-lib/actions/check-r-package@v2
